- name: Add Zabbix repository
  yum_repository:
    name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: https://repo.zabbix.com/zabbix/6.0/rhel/8/$basearch/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591

- name: Install Zabbix agent2 and needed packages
  dnf:
    name:
    - zabbix-agent2
    state: present

- name: Enable service zabbix-agent2 and ensure it is not masked
  systemd:
    name: zabbix-agent2
    enabled: yes
    masked: no

- name: Start zabbix-agent2 service
  systemd:
    name: zabbix-agent2
    state: started

- name: Add zabbix user to docker group (for containers monitoring)
  user: 
    name: zabbix
    groups: docker
    append: yes 
  notify: Restart Zabbix agent2

- name: Update Zabbix agent2 main configuration file
  template: src=zabbix_agent2.j2 dest=/etc/zabbix/zabbix_agent2.conf owner=root mode=0644 backup=yes
  notify: Restart Zabbix agent2
