- name: Ensure jenkins directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /share/jenkins

- name: Pull the latest official jenkins docker image
  docker_image:
    source: pull
    name: "jenkins/jenkins:lts"

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkins-server"
    image: "jenkins/jenkins:lts"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/share/jenkins:/var/jenkins_home"
    state: present
    recreate: no
