name: Task4-jobs

env:
  DEPLOY_VER: ${{ github.sha }}

on:
  push:
    branches:
      - main

jobs:
  Task4_push_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        directory: Task4
        image: pedanov/my-nginx
        tags: v1, latest
        registry: docker.io
        dockerfile: Task4/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
